[package]
name = "data-collector"
version = "0.3.1"
authors = ["Timo Kröger <timokroeger93@gmail.com>"]
description = "Configurable Modbus client which sends the collected data to InfluxDB"
edition = "2018"
publish = false

[dependencies]
clap = "2"
humantime = "1.2"
influx_db_client = "0.3"
log = "0.4"
modbus = { git = "https://github.com/TimoKroeger/modbus-rs", branch = "no_connect" }
serde = { version = "1.0", features = ["derive"] }
serde-humantime = "0.1"
simplelog = "0.5"
socket2 = "0.3"
toml = "0.4"
