[package]
name = "data-collector"
version = "0.7.0"
authors = ["Timo Kröger <timokroeger93@gmail.com>"]
description = "Configurable Modbus client which sends the collected data to InfluxDB"
edition = "2018"
publish = false

[dependencies]
bus = "2.2.2"
clap = "2"
crossbeam-utils = "0.6.6"
humantime = "1.2"
isahc = "0.7"
log = "0.4"
modbus = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.5"
toml = "0.5"
