[package]
name = "data-collector"
version = "0.1.0"
authors = ["Timo Kröger <timokroeger93@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
influx_db_client = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4"

[dependencies.tokio-modbus]
git = "https://github.com/uklotzde/tokio-modbus"
branch = "new_api"
default-features = false
features = ["tcp", "sync"]
