[modbus]
hostname = "127.0.0.1"
port = 502
timeout_sec = 1

[influxdb]
hostname = "http://localhost:8086"
database = "db"
username = "user"
password = "pw"

[measurements]
scan_interval_sec = 10

[[measurements.moisture]]
id = 1
register = 0
name = "Aloe Vera"

[[measurements.moisture]]
id = 2
register = 0
name = "Orchid"
