[modbus]
hostname = "127.0.0.1"
port = 502
timeout = "1s"

# [modbus_rtu]
# port = "COM1"

# [influxdb]
# hostname = "http://localhost:8086"
# database = "db"
# username = "user"
# password = "pw"

[influxdb2]
hostname = "http://localhost:9999/api/v2"
organization = "testorg"
bucket = "testbucket"
auth_token = "Ef_IVxTOA3c6YVCMN9_W5AMTjeJBiw3JG8jH3pACgBd0JtUf-5xntHBFJHkjcH8VfF4FmsFFvIA9_nGbMdLwvQ=="

[group1]
scan_interval = "1m"

[group1.measurement_registers]
moisture = 0
temperature = 1

[[group1.sensors]]
id = 1
name = "Aloe Vera"

[[group1.sensors]]
id = 2
name = "Orchid"
replaced_on = "2019-03-01"
